# Generated by Django 2.2.1 on 2019-06-04 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_priority', models.BooleanField(default=False)),
                ('age_min', models.IntegerField(default=12)),
                ('age_max', models.IntegerField(default=60)),
                ('genders_affected', models.CharField(choices=[('MF', 'Both'), ('M', 'Male'), ('F', 'Female')], default='MF', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='emergency.Condition')),
            ],
        ),
        migrations.CreateModel(
            name='Presenting_Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.Condition')),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.Emergency')),
                ('variety', models.ForeignKey(limit_choices_to={'condition': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.Condition')}, on_delete=django.db.models.deletion.CASCADE, to='emergency.Variety')),
            ],
        ),
        migrations.AddField(
            model_name='emergency',
            name='conditions',
            field=models.ManyToManyField(through='emergency.Presenting_Complaint', to='emergency.Condition'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.Emergency_Group'),
        ),
    ]
