# Generated by Django 2.2.1 on 2019-05-24 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.Condition')),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_priority', models.BooleanField(default=False)),
                ('age_min', models.IntegerField(default=12)),
                ('age_max', models.IntegerField(default=60)),
                ('genders_affected', models.CharField(choices=[('MF', 'Both'), ('M', 'Male'), ('F', 'Female')], default='MF', max_length=2)),
                ('conditions', models.ManyToManyField(to='emergency.Condition')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.Emergency_Group')),
                ('varieties', models.ManyToManyField(to='emergency.Variety')),
            ],
        ),
    ]
