# Generated by Django 2.2 on 2019-06-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='conditions',
            field=models.ManyToManyField(related_name='presenting_complaints', through='emergency.Presenting_Complaint', to='emergency.Condition'),
        ),
    ]
