# Generated by Django 2.2 on 2019-05-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_auto_20190501_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.Condition')),
            ],
        ),
        migrations.AddField(
            model_name='emergency',
            name='conditions',
            field=models.ManyToManyField(to='emergency.Condition'),
        ),
    ]
