# Generated by Django 2.2 on 2019-06-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_auto_20190614_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='conditions',
            field=models.ManyToManyField(through='emergency.Presenting_Complaint', to='emergency.Condition'),
        ),
    ]
