# Generated by Django 2.2 on 2019-05-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_auto_20190501_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency_group',
            name='parent_group',
        ),
    ]
