# Generated by Django 2.2 on 2019-05-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_remove_emergency_group_parent_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='genders',
        ),
        migrations.AddField(
            model_name='emergency',
            name='in_females',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='in_males',
            field=models.BooleanField(default=True),
        ),
    ]
