# Generated by Django 2.2 on 2019-05-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0005_auto_20190504_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='varieties',
            field=models.ManyToManyField(to='emergency.Variety'),
        ),
    ]
