# Generated by Django 2.2 on 2019-05-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0006_emergency_varieties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='in_females',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='in_males',
        ),
        migrations.AddField(
            model_name='emergency',
            name='genders_affected',
            field=models.CharField(choices=[('MF', 'Both'), ('M', 'Male'), ('F', 'Female')], default='MF', max_length=2),
        ),
    ]
