# Generated by Django 2.2 on 2019-05-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0007_auto_20190518_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='age_max',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='age_min',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emergency.Emergency_Group'),
        ),
    ]
